export const icons = {

    // Logo

    "light-theme": "images/light-themeLogo.png",
    "dark-theme": "images/dark-themeLogo.png",

    // Ikony

    about: `<i class="fa-solid fa-circle-question"></i>`,
    circuits: `<i class="fa-solid fa-diagram-project"></i>`,
    docs: `<i class="fa-solid fa-book"></i>`,
    github: `<i class="fa-brands fa-github fa-xl"></i>`,
    close: `<i class="fa-solid fa-xmark close"></i>`,
    newFile: `<i data-change="modalOpenFile" class="fa-solid fa-file openModal"></i>`,
    openFolder: `<i class="fa-solid fa-folder-open"></i>`, // openModal data-change="modalOpenFolder"
    download: `<i class="fa-solid fa-download"></i>`, // data-change="modalDownload"
    undo: `<i class="fa-solid fa-rotate-left"></i>`,
    redo: `<i class="fa-solid fa-rotate-right"></i>`,
    startSimulation: `<i class="fa-solid fa-play"></i>`,
    stopSimulation: `<i class="fa-solid fa-pause"></i>`,
    netlist: `<i data-change="modalNetlist" class="fa-solid fa-circle-nodes openModal"></i>`,
    options: `<i data-change="modalOptions" class="fa-solid fa-gear openModal"></i>`,
    caret: `<i class="fa-solid fa-caret-right fa-bounce"></i>`,
    arrowUp: `<i class="fa-solid fa-up-long toolIcon"></i>`,
    arrowDown: `<i class="fa-solid fa-down-long toolIcon"></i>`,
    arrowRight: `<i class="fa-solid fa-right-long toolIcon"></i>`,
    arrowLeft: `<i class="fa-solid fa-left-long toolIcon"></i>`,
    zoomIn: `<i class="glass fa-solid fa-magnifying-glass-plus toolIcon"></i>`,
    zoomOut:  `<i class="glass fa-solid fa-magnifying-glass-minus toolIcon"></i>`,
    rotate: `<i class="fa-solid fa-rotate toolIcon"></i>`,
    remove: `<i class="fa-solid fa-trash toolIcon"></i>`,
    clone: `<i class="fa-solid fa-clone toolIcon"></i>`,
    centerCircuit: `<i class="fa-solid fa-arrows-to-eye toolIcon"></i>`,
    oscilloscope: `<i class="fa-solid fa-wave-square"></i>`,
    resetClock: `<i class="fa-solid fa-clock-rotate-left"></i>`,
    handDrag: `<i class="fa-regular fa-hand"></i>`,
    edit: `<i class="fa-solid fa-arrow-pointer"></i>`,
    moveEditor: `<i class="fa-solid fa-arrows-up-down-left-right"></i>`,
    multipleSelect: `<i class="fa-regular fa-square"></i>`,
    removeWire: `<i class="fa-solid fa-wrench"></i>`,


    // Obrázky

    Label: "images/components/Label.png",
    Line: "images/components/Line.png",
    Box: "images/components/Box.png",
    Text: "images/components/Text.png",

    // Tutorial Gify

    Settings: "images/Gifs/Settings.gif",
    MovingEditor: "images/Gifs/MovingEditor.gif",
    AddComponents: "images/Gifs/AddComponents.gif",
    EditComponents: "images/Gifs/EditComponents.gif",
    AddWires: "images/Gifs/AddWires.gif",
    Simulate: "images/Gifs/Simulate.gif",
    OscilloscopeSettings: "images/Gifs/OscilloscopeSettings.gif",
    SaveAndLoad: "images/Gifs/SaveAndLoad.gif",

    // Ukážkové obvody obrázky

    circuit1: "images/sampleCircuits/ExclusiveOR.png",
    circuit2: "images/sampleCircuits/MajorityLogic.png",
    circuit3: "images/sampleCircuits/HalfAdder.png",
    circuit4: "images/sampleCircuits/FullAdder.png",
    circuit5: "images/sampleCircuits/1-of-4Decoder.png",
    circuit6: "images/sampleCircuits/DivideBy2.png",
    circuit7: "images/sampleCircuits/DivideBy3.png",
    circuit8: "images/sampleCircuits/PriorityEncoder.png",
    circuit9: "images/sampleCircuits/SIPO.png",
    circuit10: "images/sampleCircuits/PISO.png",
    circuit11: "images/sampleCircuits/Smiley.png",
    circuit12: "images/sampleCircuits/UpDownCounter.png",
    circuit13: "images/sampleCircuits/SRFlipFlop.png",
    circuit14: "images/sampleCircuits/4-BitRippleCounter.png",
    circuit15: "images/sampleCircuits/8-Bit-RippleCounter.png",
    circuit16: "images/sampleCircuits/3BitGrayCode.png",
    circuit17: "images/sampleCircuits/Clocked-SR-Flip-Flop.png",
    circuit18: "images/sampleCircuits/Edge-Triggered-D-Flip-Flop.png",
    circuit19: "images/sampleCircuits/Master-Slave-Flip-Flop.png",
    circuit20: "images/sampleCircuits/SynchronousCounter.png",
    circuit21: "images/sampleCircuits/2-Bit-Comparator.png",
    circuit22: "images/sampleCircuits/ALU.png",

    // Ukážkové obvody spustitelný JSON súbor

    ExclusiveOR: "circuits/Exclusive OR.json",
    MajorityLogic: "circuits/Majority Logic.json",
    HalfAdderCircuit: "circuits/Half Adder.json",
    FullAdderCircuit: "circuits/Full Adder.json",
    DecoderOneFour: "circuits/1-of-4 Decoder.json",
    DivideByTwo: "circuits/Divide-By-Two.json",
    DivideByThree: "circuits/Divide-By-Three.json",
    PriorityEncoder: "circuits/Priority Encoder.json",
    SIPO: "circuits/Serial-In-Parallel-Out.json",
    PISO: "circuits/Parallel-In-Serial-Out.json",
    Smiley: "circuits/Smiley.json",
    UpDownCounter: "circuits/Up-Down Counter.json",
    SRFlipFlop: "circuits/SR Flip-Flop.json",
    FourBitCounter: "circuits/4-Bit Ripple Counter.json",
    EightBitCounter: "circuits/8-Bit Ripple Counter.json",
    ThreeGrayCode: "circuits/3-Bit Gray Code.json",
    TwoBitComparator: "circuits/2-Bit Comparator.json",
    ClkSR: "circuits/Clocked SR Flip-Flop.json",
    EdgeTriggeredDFF: "circuits/Edge-Triggered D Flip-Flop.json",
    MSFF: "circuits/Master-Slave Flip-Flop.json",
    SyncCounter: "circuits/Synchronous Counter.json",
    ALU: "circuits/ALU.json",

        
    // Európske ikony komponentov
        
    IEC: {
        AC: "images/components/AC Source.png",
        Ammeter: "images/components/Ammeter.png",
        Capacitor: "images/components/Capacitor.png",
        CurrentSource: "images/components/Current Source.png",
        DC: "images/components/DC Source.png",
        Diode: "images/components/Diode.png",
        Ground: "images/components/Ground.png",
        Inductor: "images/components/Inductor.png",
        Led: "images/components/LED.png",
        Mosfet_n: "images/components/MOSFET-N.png",
        Mosfet_p: "images/components/MOSFET-P.png",
        NPN: "images/components/NPN.png",
        Ohmmeter: "images/components/Ohmmeter.png",
        Photoresistor: "images/components/Photoresistor.png",
        PNP: "images/components/PNP.png",
        Potentiometer: "images/components/Potentiometer.png",
        Resistor: "images/components/Resistor.png",
        Thermistor: "images/components/Thermistor.png",
        Voltmeter: "images/components/Voltmeter.png",
        Not: "images/components/NOT.png",
        Or: "images/components/OR.png",
        And: "images/components/AND.png",
        Nor: "images/components/NOR.png",
        Nand: "images/components/NAND.png",
        Xor: "images/components/XOR.png",
        Xnor: "images/components/XNOR.png",
        HighInput: "images/components/HighInput.png",
        LowInput: "images/components/LowInput.png",
        ClockGen: "images/components/ClockGen.png",
        ToggleSwitch: "images/components/ToggleSwitch.png",
        LightBulb: "images/components/LightBulb.png",
        LogicalOutput: "images/components/LogicalOutput.png",
        SevenSegDecoder: "images/components/7SegDeoder.png",
        SevenSegDisplay: "images/components/7SegDisplay.png",
        D_FlipFlop: "images/components/D_FlipFlop.png",
        T_FlipFlop: "images/components/T_FlipFlop.png",
        JK_FlipFlop: "images/components/JK_FlipFlop.png",
        Latch: "images/components/Latch.png",
        Multiplexor: "images/components/Multiplexor.png",
        Demultiplexor: "images/components/Demultiplexor.png",
        Counter: "images/components/Counter.png",
        RingCounter: "images/components/RingCounter.png",
        DecimalDisplay: "images/components/DecimalDisplay.png",
        HalfAdder: "images/components/HalfAdder.png",
        FullAdder: "images/components/FullAdder.png",
        SIPOregister: "images/components/SIPO.png",
        SequenceGen: "images/components/SequenceGenerator.png",
        ClockCounter: "images/components/ClockCounter.png",
        BinarySwitch: "images/components/BinarySwitch.png",
        LEDarray: "images/components/LEDarray.png",
        RGBLED: "images/components/RGBLED.png",
        Bus: "images/components/Bus.png",
        CustomLogic: "images/components/CustomLogic.png",
    },

    // Americké ikony komponentov

    ANSI: {

        AC: "images/components/AC SourceANSI.png",
        Ammeter: "images/components/AmmeterANSI.png",
        Capacitor: "images/components/CapacitorANSI.png",
        CurrentSource: "images/components/Current SourceANSI.png",
        DC: "images/components/DC SourceANSI.png",
        Diode: "images/components/DiodeANSI.png",
        Ground: "images/components/GroundANSI.png",
        Inductor: "images/components/InductorANSI.png",
        Led: "images/components/LEDANSI.png",
        Mosfet_n: "images/components/MOSFET-NANSI.png",
        Mosfet_p: "images/components/MOSFET-PANSI.png",
        NPN: "images/components/NPNANSI.png",
        Ohmmeter: "images/components/OhmmeterANSI.png",
        Photoresistor: "images/components/PhotoresistorANSI.png",
        PNP: "images/components/PNP.png",
        Potentiometer: "images/components/PotentiometerANSI.png",
        Resistor: "images/components/ResistorANSI.png",
        Thermistor: "images/components/ThermistorANSI.png",
        Voltmeter: "images/components/VoltmeterANSI.png",
        Not: "images/components/NOTANSI.png",
        Or: "images/components/ORANSI.png",
        And: "images/components/ANDANSI.png",
        Nor: "images/components/NORANSI.png",
        Nand: "images/components/NANDANSI.png",
        Xor: "images/components/XORANSI.png",
        Xnor: "images/components/XNORANSI.png",
        HighInput: "images/components/HighInputANSI.png",
        LowInput: "images/components/LowInputANSI.png",
        ClockGen: "images/components/ClockGenANSI.png",
        ToggleSwitch: "images/components/ToggleSwitchANSI.png",
        LightBulb: "images/components/LightBulbANSI.png",
        LogicalOutput: "images/components/LogicalOutputANSI.png",
        SevenSegDecoder: "images/components/7SegDecoderANSI.png",
        SevenSegDisplay: "images/components/7SegDisplayANSI.png",
        D_FlipFlop: "images/components/D_FlipFlopANSI.png",
        T_FlipFlop: "images/components/T_FlipFlopANSI.png",
        JK_FlipFlop: "images/components/JK_FlipFlopANSI.png",
        Latch: "images/components/LatchANSI.png",
        Multiplexor: "images/components/MultiplexorANSI.png",
        Demultiplexor: "images/components/DemultiplexorANSI.png",
        Counter: "images/components/CounterANSI.png",
        RingCounter: "images/components/RingCounter.png",
        DecimalDisplay: "images/components/DecimalDisplayANSI.png",
        HalfAdder: "images/components/HalfAdderANSI.png",
        FullAdder: "images/components/FullAdderANSI.png",
        SIPOregister: "images/components/SIPOANSI.png",
        SequenceGen: "images/components/SequenceGeneratorANSI.png",
        ClockCounter: "images/components/ClockCounterANSI.png",
        BinarySwitch: "images/components/BinarySwitchANSI.png",
        LEDarray: "images/components/LEDarrayANSI.png",
        RGBLED: "images/components/RGBLEDANSI.png",
        Bus: "images/components/BusANSI.png",
        CustomLogic: "images/components/CustomLogicANSI.png",
    
    }
    


}


