var lang = {

    //Preklad do slovenčiny

    // Komponenty a súčiastky

    slovak: {
        Resistor: "Rezistor",
        Capacitor: "Kondenzátor",
        Inductor: "Cievka",
        Variable_resistor: "Nastaviteľný rezistor",
        Photoresistor: "Fotorezistor",
        Thermistor: "Termistor",
        Ground: "Zem",
        DC_Source: "DC Zdroj",
        AC_Source:"AC Zdroj",
        Voltmeter: "Voltmeter",
        Ammeter: "Ampérmeter",
        Ohmmeter: "Ohmmeter",
        Diode: "Dióda",
        NPN: "NPN Tranzistor",
        PNP: "PNP Tranzistor",
        MOSFET_N: "MOSFET-N",
        MOSFET_P: "MOSFET-P",
        LED: "LED",
        Meters: "Meracie Prístroje",
        Passive: "Pasívne Súčiastky",
        Sources: "Zdroje",
        Active: "Aktívne Súčiastky",
        Logical: "Logické Brány",
        Not: "NOT Brána",
        Or: "OR Brána",
        And: "AND Brána",
        Nor: "NOR Brána",
        Nand: "NAND Brána",
        Xor: "XOR Brána",
        Xnor: "XNOR Brána",
        Inputs: "Logické Vstupy",
        LowInput: "Logická Nula",
        HighInput: "Logická Jednotka",
        ClockGen: "Generátor Impulzov",
        ToggleSwitch: "Vypínač",
        Outputs: "Logické Výstupy",
        Bulb: "Žiarovka",
        LogicalOutput: "Logický Výstup",
        Labels: "Označenia",
        Text: "Text",
        Box: "Skupina",
        Line: "Čiara",
        Label: "Štítok",


        // Označenia tlačidiel, menu, nastavení

        Welcome: "Vitajte v LogicSim!",
        About: "O programe",
        News: "Novinky",
        Circuits: "Obvody",
        Docs: "Dokumentácia",
        SignIn: "Prihlásiť sa",
        Enter: "Zadať",
        Github: "GitHub",
        Cancel: "Zrušiť",
        Close: "Zavrieť",
        Save: "Uložiť",
        Dont_save: "Neuložiť",
        projectTitle: "Zadaj názov projektu",
        Options: "Nastavenia",
        themeText: "Zmeň farebný motív",
        languageText: "Zmeň jazyk",
        displayText: "Európske súčiastky",
        valuesText: "Ukáž hodnoty komponentov",
        partsPosition: "Zmeň stranu menu komponentov",
        grid: "Ukáž štvorcovú mriežku",
        Dark_theme: "Tmavá",
        Light_theme: "Svetlá",
        Red_theme: "Červená",
        Blue_theme: "Modrá",
        Circuit_netlist: "Textový zoznam obvodu",
        VoltageColor: "Zmeniť farbu napätia",
        UntitledCircuit: "Bez názvu",
        StartTutorial: "Začať tutoriál" ,
        SkipTutorial: "Preskočiť",
        Show: "Znova nezobrazovať",
        Next: "Ďalej",
        Previous: "Späť",
        Finish: "Dokončiť",
        ZoomIn: "Priblížiť",
        ZoomOut: "Oddialiť",
        Rotate: "Otočiť",
        Delete: "Zmazať",
        Clone: "Kopírovať",
        Center: "Centrovať",

        // Obvody

        Circuits: "Obvody",
        SampleCir1: "Obvod1",
        SampleCir2: "Obvod2",
        SampleCir3: "Obvod3",
        SampleCir4: "Obvod4",
        SampleCir5: "Obvod5",
        SampleCir6: "Obvod6",
        SampleCir7: "Obvod7",
        SampleCir8: "Obvod8",
        SampleCir9: "Obvod9",
        SampleCir10: "Obvod10",
        SampleCir11: "Obvod11",
        SampleCir12: "Obvod12",
        SampleCir13: "Obvod13",
        SampleCir14: "Obvod14",
        SampleCir15: "Obvod15",
        SampleCir16: "Obvod16",
        SampleCir17: "Obvod17",
        SampleCir18: "Obvod18",
        
        // Oznamy a texty používateľom

        mainFunctions: "Hlavné Funkcie",

        circuitDesign: "Návrh Obvodov",
        circuitDesignText: "Užívatelia môžu jednoducho navrhovať obvody prostredníctvom drag-and-drop rozhrania.",

        simulation: "Simulácia v Reálnom Čase",
        simulationText: "Obvody sú simulované v reálnom čase, s možnosťou pozorovania hodnôt na jednotlivých výstupoch a vstupoch.",

        tutorial: "Tutoriál and Inštrukcie",
        tutorialText: "Aplikácia obsahuje tutoriál a krok-za-krokom inštrukcie pre nových užívateľov.",

        projectName: "Názov projektu",
        author: "Autor",
        aboutText: "Tento maturitný projekt predstavuje interaktívny simulátor logických obvodov, ktorý umožňuje študentom a nadšencom z oblasti elektroniky a informatiky experimentovať s digitálnymi obvodmi v reálnom čase. Vytvorený v jazykoch JavaScript, HTML a CSS, tento nástroj využíva knižnicu Konva.js pre vizualizáciu komponentov a obvodov na plátne.",

        saveText: "Ste si istý, že chcete pokračovať bez uloženia aktuálneho projektu?",
        Save_project: "Uložiť projekt?",

        WelcomeTitle: "Simulátor Logických Obvodov",
        WelcomeText: "Vitajte na stránke LogicSim! Vaše jediné miesto pre všetky vaše potreby v oblasti simulácie obvodov. Či už ste skúsený nadšenec elektrotechniky alebo zvedavý začiatočník. S intuitívnym rozhraním a rozsiahlou knižnicou komponentov na dosah ruky, môžete oživiť svoje nápady a pozorovať magický svet elektronických obvodov v akcii. Pripojte sa k našej komunite vášnivých inžinierov a nadšencov dnes a nechajte LogicSim byť vaším dôveryhodným spoločníkom na vašej elektrizujúcej ceste do sveta obvodov. Veselé simulovanie!",

        Tutorial1: "",
        Tutorial2: "",
        Tutorial3: "",
        Tutorial4: "",
        Tutorial5: "",

    },
    
    //Preklad do angličtiny

    english: {
        // Komponenty a grafické widgety do editora

        Resistor: "Resistor",
        Capacitor: "Capacitor",
        Inductor: "Inductor",
        Variable_resistor: "Variable Resistor",
        Photoresistor: "Photoresistor",
        Thermistor: "Thermistor",
        Ground: "Ground",
        DC_Source: "DC Source",
        AC_Source:"AC Source",
        Voltmeter: "Voltmeter",
        Ammeter: "Ammeter",
        Ohmmeter: "Ohmmeter",
        Diode: "Diode",
        NPN: "NPN Transistor",
        PNP: "PNP Transistor",
        MOSFET_N: "MOSFET-N",
        MOSFET_P: "MOSFET-P",
        LED: "LED",
        Meters: "Meters",
        Passive: "Passive",
        Sources: "Sources",
        Active: "Active",
        Logical: "Logical Gates",
        Not: "NOT Gate",
        Or: "OR Gate",
        And: "AND Gate",
        Nor: "NOR Gate",
        Nand: "NAND Gate",
        Xor: "XOR Gate",
        Xnor: "XNOR Gate",
        Inputs: "Logical Inputs",
        LowInput: "Low Input",
        HighInput: "High Input",
        ClockGen: "Clock Generator",
        ToggleSwitch: "Toggle Switch",
        Outputs: "Logical Outputs",
        Bulb: "Light Bulb",
        LogicalOutput: "Logical Output",
        Labels: "Labels",
        Text: "Text",
        Box: "Box",
        Line: "Line",
        Label: "Label",

        // Označenia tlačidiel, menu, nastavení

        Welcome: "Welcome to LogicSim!",
        About: "About",
        News: "News",
        Circuits: "Circuits",
        Docs: "Documentation",
        SignIn: "Sign In",
        Enter: "Enter",
        Github: "GitHub",
        Cancel: "Cancel",
        Close: "Close",
        Save: "Save",
        Dont_save: "Don't save",
        projectTitle: "Enter your project title",
        Options: "Options",
        themeText: "Change color theme",
        languageText: "Change language",
        displayText: "European parts",
        valuesText: "Show component values",
        partsPosition: "Change components menu position",
        grid: "Show grid",
        Dark_theme: "Dark",
        Light_theme: "Light",
        Red_theme: "Red",
        Blue_theme: "Blue",
        Circuit_netlist: "Circuit netlist",
        VoltageColor: "Change voltage color",
        UntitledCircuit: "Untitled circuit",
        StartTutorial: "Start tutorial" ,
        SkipTutorial: "Skip tutorial",
        Show: "Don't show again",
        Next: "Next",
        Previous: "Previous",
        Finish: "Finish",
        ZoomIn: "Zoom-In",
        ZoomOut: "Zoom-Out",
        Rotate: "Rotate",
        Delete: "Delete",
        Clone: "Copy",
        Center: "Center",
        
        // Obvody

        Circuits: "Circuits",
        SampleCir1: "Circuit1",
        SampleCir2: "Circuit2",
        SampleCir3: "Circuit3",
        SampleCir4: "Circuit4",
        SampleCir5: "Circuit5",
        SampleCir6: "Circuit6",
        SampleCir7: "Circuit7",
        SampleCir8: "Circuit8",
        SampleCir9: "Circuit9",
        SampleCir10: "Circuit10",
        SampleCir11: "Circuit11",
        SampleCir12: "Circuit12",
        SampleCir13: "Circuit13",
        SampleCir14: "Circuit14",
        SampleCir15: "Circuit15",
        SampleCir16: "Circuit16",
        SampleCir17: "Circuit17",
        SampleCir18: "Circuit18",
        
        // Oznamy a texty používateľom

        mainFunctions: "Main Functions",

        circuitDesign: "Circuit Design",
        circuitDesignText: "Users can easily design circuits through a drag-and-drop interface.",

        simulation: "Real Time Simulation",
        simulationText: "Circuits are simulated in real time, with the possibility of observing values ​​at individual outputs and inputs.",

        tutorial: "Tutorial and Instructions",
        tutorialText: "The application includes a tutorial and step-by-step instructions for new users.",

        projectName: "Project name",
        author: "Author",
        aboutText: "This graduation project presents an interactive logic circuit simulator that allows students and electronics and computer science enthusiasts to experiment with digital circuits in real time. Built in JavaScript, HTML and CSS, this tool uses the Konva.js library to visualize components and circuits on the canvas.",

        saveText: "Are you sure you want to continue without saving your project?",
        Save_project: "Save current project?",

        WelcomeTitle: "Logical Circuit Simulator",
        WelcomeText: "Welcome to LogicSim! Your one stop shop for all your circuit simulation needs. Whether you are an experienced electrical engineering enthusiast or a curious beginner. With an intuitive interface and an extensive library of components at your fingertips, you can bring your ideas to life and watch the magical world of electronic circuits in action. Join our community of passionate engineers and enthusiasts today and let LogicSim be your trusted companion on your electrifying journey into the world of circuits. Happy simulating!",

        Tutorial1: "",
        Tutorial2: "",
        Tutorial3: "",
        Tutorial4: "",
        Tutorial5: "",
    },
}